/**
 * ✅ ENTELECHIA: Purity Guards Code Generator
 * 
 * Generates TypeScript purity guards descriptors from canonical purity guards.
 * 
 * PRINCIPLE: FORM → ACT → STATE → RUNTIME
 * - FORM: Purity Guards YAML files
 * - ACT: This generator creates STATE artifacts
 * - STATE: Generated guards.generated.ts
 * - RUNTIME: Guards consumed by runtime sentinel
 */

import type { CanonicalPurityGuardDescriptor } from '../../purity-guards/purity-guards-canonicalizer.js'

/**
 * Generate purity guards TypeScript code
 */
export function generatePurityGuardsCode(
  purityGuards: Map<string, CanonicalPurityGuardDescriptor>
): string {
  const lines: string[] = []
  
  lines.push('/**')
  lines.push(' * ✅ ENTELECHIA: Purity Guards (Generated)')
  lines.push(' * ')
  lines.push(' * This file is AUTO-GENERATED by ACT Engine Phase 9.2.')
  lines.push(' * DO NOT EDIT MANUALLY. All changes must be made in entelechia-form/purity-guards/*.yaml')
  lines.push(' * ')
  lines.push(' * Generated:', new Date().toISOString())
  lines.push(' */')
  lines.push('')
  
  lines.push('export interface PurityGuardViolation {')
  lines.push('  pattern: string')
  lines.push('  matcher: {')
  lines.push('    imports?: Array<{ from: string; in?: string; notIn?: string }>')
  lines.push('    identifiers?: Array<{ pattern: string; description?: string; in?: string; notIn?: string; matching?: string }>')
  lines.push('    filePatterns?: Array<{ pattern: string; exclude?: string }>')
  lines.push('    gitStatus?: "modified" | "added" | "deleted"')
  lines.push('    notIn?: string')
  lines.push('    notGeneratedBy?: string')
  lines.push('    missing?: string')
  lines.push('    scope?: string')
  lines.push('    comparison?: { form: string; act: string; check: string }')
  lines.push('    semantic?: string')
  lines.push('  }')
  lines.push('  telosViolated: string')
  lines.push('  resolutionSteps: string[]')
  lines.push('}')
  lines.push('')
  
  lines.push('export interface PurityGuardInvariant {')
  lines.push('  id: string')
  lines.push('  name: string')
  lines.push('  description: string')
  lines.push('  severity: "error" | "warn"')
  lines.push('  enforcement: "build" | "runtime" | "both"')
  lines.push('  violations: PurityGuardViolation[]')
  lines.push('}')
  lines.push('')
  
  lines.push('export interface PurityGuardDescriptor {')
  lines.push('  guardType: "architectural" | "form" | "act" | "state" | "intent" | "epistemic"')
  lines.push('  metadata: {')
  lines.push('    version: string')
  lines.push('    description?: string')
  lines.push('    lastUpdated?: string')
  lines.push('  }')
  lines.push('  invariants: PurityGuardInvariant[]')
  lines.push('}')
  lines.push('')
  
  // Generate guard registry
  lines.push('export const purityGuardsRegistry = new Map<string, PurityGuardDescriptor>([')
  
  for (const [guardType, guard] of purityGuards.entries()) {
    lines.push(`  [`)
    lines.push(`    "${guardType}",`)
    lines.push(`    {`)
    lines.push(`      guardType: "${guard.guardType}",`)
    lines.push(`      metadata: {`)
    lines.push(`        version: "${guard.metadata.version}",`)
    if (guard.metadata.description) {
      lines.push(`        description: ${JSON.stringify(guard.metadata.description)},`)
    }
    if (guard.metadata.lastUpdated) {
      lines.push(`        lastUpdated: "${guard.metadata.lastUpdated}",`)
    }
    lines.push(`      },`)
    lines.push(`      invariants: [`)
    
    for (const invariant of guard.invariants) {
      lines.push(`        {`)
      lines.push(`          id: "${invariant.id}",`)
      lines.push(`          name: "${invariant.name}",`)
      lines.push(`          description: ${JSON.stringify(invariant.description)},`)
      lines.push(`          severity: "${invariant.severity}",`)
      lines.push(`          enforcement: "${invariant.enforcement}",`)
      lines.push(`          violations: [`)
      
      for (const violation of invariant.violations) {
        lines.push(`            {`)
        lines.push(`              pattern: ${JSON.stringify(violation.pattern)},`)
        lines.push(`              matcher: ${JSON.stringify(violation.matcher)},`)
        lines.push(`              telosViolated: ${JSON.stringify(violation.telosViolated)},`)
        lines.push(`              resolutionSteps: ${JSON.stringify(violation.resolutionSteps)},`)
        lines.push(`            },`)
      }
      
      lines.push(`          ],`)
      lines.push(`        },`)
    }
    
    lines.push(`      ],`)
    lines.push(`    },`)
    lines.push(`  ],`)
  }
  
  lines.push('])')
  lines.push('')
  
  // Generate helper functions
  lines.push('export function getPurityGuard(guardType: string): PurityGuardDescriptor | undefined {')
  lines.push('  return purityGuardsRegistry.get(guardType)')
  lines.push('}')
  lines.push('')
  
  lines.push('export function getAllPurityGuards(): PurityGuardDescriptor[] {')
  lines.push('  return Array.from(purityGuardsRegistry.values())')
  lines.push('}')
  lines.push('')
  
  lines.push('export function getPurityGuardInvariant(guardType: string, invariantId: string): PurityGuardInvariant | undefined {')
  lines.push('  const guard = purityGuardsRegistry.get(guardType)')
  lines.push('  if (!guard) return undefined')
  lines.push('  return guard.invariants.find(inv => inv.id === invariantId)')
  lines.push('}')
  lines.push('')
  
  return lines.join('\n')
}

