/**
 * ✅ ENTELECHIA: Surface Code Generator
 * 
 * Generates TypeScript code for surface descriptors.
 * 
 * PRINCIPLE: Generated code is deterministic and never edited manually.
 * 
 * FORM → ACT → STATE → RUNTIME:
 * - FORM: *.view.yaml files
 * - ACT: surface-canonicalizer.ts
 * - STATE: This generator → *.surface.generated.ts
 * - RUNTIME: SurfaceRenderer component
 */

import type { CanonicalSurfaceDescriptor } from '../../surfaces/surface-canonicalizer.js'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Generate banner for generated files
 */
function generateBanner(sourceFile: string): string {
  return `/**
 * ⚠️ GENERATED FILE — DO NOT EDIT
 * 
 * This file is generated by act-engine from ${sourceFile}.
 * Any manual edits will be overwritten.
 * 
 * Source: ${sourceFile}
 * Generated: ${new Date().toISOString()}
 */`
}

/**
 * Generate TypeScript code for surface descriptor
 */
export function generateSurfaceCode(
  descriptor: CanonicalSurfaceDescriptor,
  outputPath: string,
  sourceFile: string
): void {
  const code = `${generateBanner(sourceFile)}

/**
 * Canonical surface descriptor
 * 
 * Generated from surface view YAML via surface-canonicalizer.
 * This is the single source of truth for surface structure.
 */
export const surfaceDescriptor: {
  version: string
  generatedAt: string
  views: Array<{
    id: string
    title: string
    kind: string
    layout: string
    sections: Array<{
      id: string
      title?: string
      kind: string
      blocks: Array<{
        id: string
        type: string
        props: Record<string, any>
      }>
      layout: string
      columns?: number
    }>
    description?: string
    tags?: string[]
  }>
} = ${JSON.stringify(descriptor, null, 2)} as const

/**
 * Get surface view by ID
 */
export function getSurfaceView(id: string) {
  return surfaceDescriptor.views.find(v => v.id === id)
}

/**
 * Get all views
 */
export function getAllViews() {
  return surfaceDescriptor.views
}

/**
 * Get views by kind
 */
export function getViewsByKind(kind: string) {
  return surfaceDescriptor.views.filter(v => v.kind === kind)
}
`

  writeFileSync(outputPath, code, 'utf-8')
}

